# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'


- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'custom'
    commandOptions: 'version'
    outputTo: 'console'
    customCommand: 'version'
    environmentServiceNameAzureRM: 'terraform'


- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'terraform'
    backendAzureRmResourceGroupName: 'Devopsrg'
    backendAzureRmStorageAccountName: 'terraforminfradfevops'
    backendAzureRmContainerName: 'blob'
    backendAzureRmKey: 'terraform.tfstate'

 - task: TerraformTaskV4@4
   inputs:
     provider: 'azurerm'
     command: 'validate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-out=tfplan'
    environmentServiceNameAzureRM: 'terraform'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve tfplan'
    environmentServiceNameAzureRM: 'terraform'
